In [1]:
# Importing the libraries
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [2]:
dataset = pd.read_csv('Churn_Modelling.csv')

In [3]:
dataset

RowNumber  CustomerId    Surname  CreditScore Geography  Gender  Age  \
0             1    15634602   Hargrave          619    France  Female   42   
1             2    15647311       Hill          608     Spain  Female   41   
2             3    15619304       Onio          502    France  Female   42   
3             4    15701354       Boni          699    France  Female   39   
4             5    15737888   Mitchell          850     Spain  Female   43   
...         ...         ...        ...          ...       ...     ...  ...   
9995       9996    15606229   Obijiaku          771    France    Male   39   
9996       9997    15569892  Johnstone          516    France    Male   35   
9997       9998    15584532        Liu          709    France  Female   36   
9998       9999    15682355  Sabbatini          772   Germany    Male   42   
9999      10000    15628319     Walker          792    France  Female   28   

      Tenure    Balance  NumOfProducts  HasCrCard  IsActiveMember  \
0          2       0.00              1          1               1   
1          1   83807.86              1          0               1   
2          8  159660.80              3          1               0   
3          1       0.00              2          0               0   
4          2  125510.82              1          1               1   
...      ...        ...            ...        ...             ...   
9995       5       0.00              2          1               0   
9996      10   57369.61              1          1               1   
9997       7       0.00              1          0               1   
9998       3   75075.31              2          1               0   
9999       4  130142.79              1          1               0   

      EstimatedSalary  Exited  
0           101348.88       1  
1           112542.58       0  
2           113931.57       1  
3            93826.63       0  
4            79084.10       0  
...               ...     ...  
9995         96270.64       0  
9996        101699.77       0  
9997         42085.58       1  
9998         92888.52       1  
9999         38190.78       0  

[10000 rows x 14 columns]

In [4]:
X = dataset.iloc[:, 3:13].values
y = dataset.iloc[:, 13].values

In [5]:
X

array([[619, 'France', 'Female', ..., 1, 1, 101348.88],
       [608, 'Spain', 'Female', ..., 0, 1, 112542.58],
       [502, 'France', 'Female', ..., 1, 0, 113931.57],
       ...,
       [709, 'France', 'Female', ..., 0, 1, 42085.58],
       [772, 'Germany', 'Male', ..., 1, 0, 92888.52],
       [792, 'France', 'Female', ..., 1, 0, 38190.78]], dtype=object)

In [6]:
y

array([1, 0, 1, ..., 1, 1, 0], dtype=int64)

In [7]:
# Encoding categorical data
from sklearn.preprocessing import LabelEncoder, OneHotEncoder
labelencoder_X_1 = LabelEncoder()
X[:, 1] = labelencoder_X_1.fit_transform(X[:, 1])
labelencoder_X_2 = LabelEncoder()
X[:, 2] = labelencoder_X_2.fit_transform(X[:, 2])
onehotencoder = OneHotEncoder(categorical_features = [1])
X = onehotencoder.fit_transform(X).toarray()
X = X[:, 1:]

C:\Users\GodHand\Anaconda3\lib\site-packages\sklearn\preprocessing\_encoders.py:415: FutureWarning: The handling of integer data will change in version 0.22. Currently, the categories are determined based on the range [0, max(values)], while in the future they will be determined based on the unique values.
If you want the future behaviour and silence this warning, you can specify "categories='auto'".
In case you used a LabelEncoder before this OneHotEncoder to convert the categories to integers, then you can now use the OneHotEncoder directly.
  warnings.warn(msg, FutureWarning)
C:\Users\GodHand\Anaconda3\lib\site-packages\sklearn\preprocessing\_encoders.py:451: DeprecationWarning: The 'categorical_features' keyword is deprecated in version 0.20 and will be removed in 0.22. You can use the ColumnTransformer instead.
  "use the ColumnTransformer instead.", DeprecationWarning)


In [8]:
# Splitting the dataset into the Training set and Test set
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 0)

In [9]:
# Feature Scaling
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [10]:
#let's build ANN

In [11]:
import keras

Using TensorFlow backend.


In [12]:
from keras.models import Sequential
from keras.layers import Dense

In [13]:
#initialising
classifier = Sequential()

In [14]:
# Adding the input layer and the first hidden layer
classifier.add(Dense(units = 6, kernel_initializer = 'uniform', activation = 'relu', input_dim = 11))

In [15]:
# Adding the second hidden layer
classifier.add(Dense(units = 6, kernel_initializer = 'uniform', activation = 'relu'))

In [16]:
# Adding the output layer
classifier.add(Dense(units = 1, kernel_initializer = 'uniform', activation = 'sigmoid'))

In [17]:
#compiling ANN
classifier.compile(optimizer = 'adam',loss = 'binary_crossentropy',metrics = ['accuracy'])

In [18]:
# Fitting the ANN to the Training set
classifier.fit(X_train,y_train,batch_size = 10,epochs = 100 )

Epoch 1/100
8000/8000 [==============================] - 2s 231us/step - loss: 0.4913 - accuracy: 0.7959
Epoch 2/100
8000/8000 [==============================] - 1s 161us/step - loss: 0.4286 - accuracy: 0.7960
Epoch 3/100
8000/8000 [==============================] - 1s 182us/step - loss: 0.4232 - accuracy: 0.7960
Epoch 4/100
8000/8000 [==============================] - 1s 153us/step - loss: 0.4184 - accuracy: 0.8134
Epoch 5/100
8000/8000 [==============================] - 1s 152us/step - loss: 0.4148 - accuracy: 0.8284
Epoch 6/100
8000/8000 [==============================] - 1s 152us/step - loss: 0.4111 - accuracy: 0.8321
Epoch 7/100
8000/8000 [==============================] - 2s 188us/step - loss: 0.4082 - accuracy: 0.8329
Epoch 8/100
8000/8000 [==============================] - 1s 165us/step - loss: 0.4060 - accuracy: 0.8311
Epoch 9/100
8000/8000 [==============================] - 1s 152us/step - loss: 0.4046 - accuracy: 0.8345
Epoch 10/100
8000/8000 [==============================]

8000/8000 [==============================] - 1s 169us/step - loss: 0.3934 - accuracy: 0.8351
Epoch 79/100
8000/8000 [==============================] - 1s 167us/step - loss: 0.3941 - accuracy: 0.8372
Epoch 80/100
8000/8000 [==============================] - 1s 168us/step - loss: 0.3927 - accuracy: 0.8367
Epoch 81/100
8000/8000 [==============================] - 1s 168us/step - loss: 0.3938 - accuracy: 0.8353
Epoch 82/100
8000/8000 [==============================] - 2s 196us/step - loss: 0.3937 - accuracy: 0.8365
Epoch 83/100
8000/8000 [==============================] - 2s 197us/step - loss: 0.3933 - accuracy: 0.8369
Epoch 84/100
8000/8000 [==============================] - 1s 169us/step - loss: 0.3937 - accuracy: 0.8378
Epoch 85/100
8000/8000 [==============================] - 1s 169us/step - loss: 0.3935 - accuracy: 0.8371
Epoch 86/100
8000/8000 [==============================] - 1s 168us/step - loss: 0.3937 - accuracy: 0.8381
Epoch 87/100
8000/8000 [==============================] - 1

In [19]:
y_predict = classifier.predict(X_test)

In [20]:
y_predict

array([[0.18755409],
       [0.28990966],
       [0.20322186],
       ...,
       [0.16453749],
       [0.11483496],
       [0.14282615]], dtype=float32)

In [21]:
y_predict = (y_predict > 0.5)

In [22]:
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test,y_predict)

In [23]:
cm

array([[1543,   52],
       [ 259,  146]], dtype=int64)

In [24]:
(1554 + 126)/2000


0.84

In [25]:
type(X_train)

numpy.ndarray

In [26]:
from keras.wrappers.scikit_learn import KerasClassifier
from sklearn.model_selection import cross_val_score
from keras.models import Sequential
from keras.layers import Dense

In [ ]:
def build_classifier():
    classifier = Sequential()
    classifier.add(Dense(units = 6, kernel_initializer = 'uniform', activation = 'relu', input_dim = 11))
    classifier.add(Dense(units = 6, kernel_initializer = 'uniform', activation = 'relu'))
    classifier.add(Dense(units = 1, kernel_initializer = 'uniform', activation = 'sigmoid'))
    classifier.compile(optimizer = 'adam',loss = 'binary_crossentropy',metrics = ['accuracy'])
    return classifier
classifier = KerasClassifier(build_fn = build_classifier,batch_size = 10,epochs = 100)
accuracies = cross_val_score(estimator = classifier,X = X_train ,y = y_train,cv = 10,n_jobs = -1)

In [ ]:
mean = accuracies.mean()

In [ ]:
var = accuracies.std()