In [19]:
import pandas as pd
import numpy as np
from sklearn import linear_model

In [20]:
df = pd.read_csv('housePrice.csv')
df

area  bedrooms  age    price
0   2600       3.0   20   550000
1    300       4.0   15   600000
2   3200       NaN   18   700000
3   3600       3.0   19   450000
4   4000       5.0   16   670000
5   4200       2.0   14   235600
6   4400       6.0   15   890000
7   4600       4.0   12   750000
8   4800       3.0   13   123456
9   5000       NaN  154   980000
10  5200       6.0   16   768000
11  5400       3.0   17   789456
12  5600       7.0   23   980345
13  5800       8.0    9   234000
14  6000       9.0   12   456789
15  6200       NaN   24   890456
16  6400       6.0   19  1234098
17  6800       8.0   18  1239945

In [21]:
df.bedrooms.median()

5.0

In [22]:
import math
median_bedrooms = math.floor(df.bedrooms.median())
median_bedrooms

5

In [23]:
df.bedrooms.fillna(median_bedrooms)
df

area  bedrooms  age    price
0   2600       3.0   20   550000
1    300       4.0   15   600000
2   3200       NaN   18   700000
3   3600       3.0   19   450000
4   4000       5.0   16   670000
5   4200       2.0   14   235600
6   4400       6.0   15   890000
7   4600       4.0   12   750000
8   4800       3.0   13   123456
9   5000       NaN  154   980000
10  5200       6.0   16   768000
11  5400       3.0   17   789456
12  5600       7.0   23   980345
13  5800       8.0    9   234000
14  6000       9.0   12   456789
15  6200       NaN   24   890456
16  6400       6.0   19  1234098
17  6800       8.0   18  1239945

In [24]:
df.bedrooms.fillna(median_bedrooms)

0     3.0
1     4.0
2     5.0
3     3.0
4     5.0
5     2.0
6     6.0
7     4.0
8     3.0
9     5.0
10    6.0
11    3.0
12    7.0
13    8.0
14    9.0
15    5.0
16    6.0
17    8.0
Name: bedrooms, dtype: float64

In [25]:
df

area  bedrooms  age    price
0   2600       3.0   20   550000
1    300       4.0   15   600000
2   3200       NaN   18   700000
3   3600       3.0   19   450000
4   4000       5.0   16   670000
5   4200       2.0   14   235600
6   4400       6.0   15   890000
7   4600       4.0   12   750000
8   4800       3.0   13   123456
9   5000       NaN  154   980000
10  5200       6.0   16   768000
11  5400       3.0   17   789456
12  5600       7.0   23   980345
13  5800       8.0    9   234000
14  6000       9.0   12   456789
15  6200       NaN   24   890456
16  6400       6.0   19  1234098
17  6800       8.0   18  1239945

In [26]:
df.bedrooms = df.bedrooms.fillna(median_bedrooms)

In [27]:
df

area  bedrooms  age    price
0   2600       3.0   20   550000
1    300       4.0   15   600000
2   3200       5.0   18   700000
3   3600       3.0   19   450000
4   4000       5.0   16   670000
5   4200       2.0   14   235600
6   4400       6.0   15   890000
7   4600       4.0   12   750000
8   4800       3.0   13   123456
9   5000       5.0  154   980000
10  5200       6.0   16   768000
11  5400       3.0   17   789456
12  5600       7.0   23   980345
13  5800       8.0    9   234000
14  6000       9.0   12   456789
15  6200       5.0   24   890456
16  6400       6.0   19  1234098
17  6800       8.0   18  1239945

In [28]:
reg = linear_model.LinearRegression()
reg.fit(df[['area','bedrooms','age']],df.price)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [29]:
reg.coef_

array([   42.75034317, 39147.91553974,  2737.57038734])

In [30]:
reg.intercept_

230951.52008043358

In [31]:
reg.predict([[3000,3,40]])

array([586149.11171026])

In [32]:
42.75034317*3000 + 39147.91553974*3 + 2737.57038734*40 + 230951.52008043358

586149.1117032536

In [33]:
reg.predict([[2500,4,5]])

array([508106.89210681])

In [34]:
import pickle

In [35]:
with open('model_pickel','wb') as file:
    pickle.dump(reg,file)

In [36]:
with open('model_pickel','rb') as f:
    mp = pickle.load(f)

In [37]:
mp.coef_

array([   42.75034317, 39147.91553974,  2737.57038734])

In [38]:
mp.intercept_

230951.52008043358

In [40]:
mp.predict([[2500,4,5]])

array([508106.89210681])

In [41]:
from sklearn.externals import joblib

C:\Users\GodHand\Anaconda3\lib\site-packages\sklearn\externals\joblib\__init__.py:15: DeprecationWarning: sklearn.externals.joblib is deprecated in 0.21 and will be removed in 0.23. Please import this functionality directly from joblib, which can be installed with: pip install joblib. If this warning is raised when loading pickled models, you may need to re-serialize those models with scikit-learn 0.21+.
  warnings.warn(msg, category=DeprecationWarning)


In [42]:
joblib.dump(reg,'model_joblib')

['model_joblib']

In [43]:
mj = joblib.load('model_joblib')

In [44]:
mj.coef_

array([   42.75034317, 39147.91553974,  2737.57038734])

In [45]:
mj.intercept_

230951.52008043358

In [46]:
mj.predict([[2500,4,5]])

array([508106.89210681])