In [1]:
import cv2

ModuleNotFoundError: No module named 'cv2'

In [2]:
import cv

ModuleNotFoundError: No module named 'cv'

In [3]:
import cv2

ModuleNotFoundError: No module named 'cv2'

In [4]:
import numpy as np

In [5]:
import cv2


ModuleNotFoundError: No module named 'cv2'

In [6]:
my_list = [1,2,3]

In [7]:
my_list

[1, 2, 3]

In [8]:
arr = np.array(my_list)

In [9]:
arr

array([1, 2, 3])

In [10]:
x = [[1,2,3] ,[4,56,5],[7,8,9]]

In [11]:
n = np.array(x)

In [12]:
n

array([[ 1,  2,  3],
       [ 4, 56,  5],
       [ 7,  8,  9]])

In [13]:
np.arange(0,10,2)

array([0, 2, 4, 6, 8])

In [17]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [18]:
np.zeros((5,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [19]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [21]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [23]:
np.linspace(0,5)

array([0.        , 0.10204082, 0.20408163, 0.30612245, 0.40816327,
       0.51020408, 0.6122449 , 0.71428571, 0.81632653, 0.91836735,
       1.02040816, 1.12244898, 1.2244898 , 1.32653061, 1.42857143,
       1.53061224, 1.63265306, 1.73469388, 1.83673469, 1.93877551,
       2.04081633, 2.14285714, 2.24489796, 2.34693878, 2.44897959,
       2.55102041, 2.65306122, 2.75510204, 2.85714286, 2.95918367,
       3.06122449, 3.16326531, 3.26530612, 3.36734694, 3.46938776,
       3.57142857, 3.67346939, 3.7755102 , 3.87755102, 3.97959184,
       4.08163265, 4.18367347, 4.28571429, 4.3877551 , 4.48979592,
       4.59183673, 4.69387755, 4.79591837, 4.89795918, 5.        ])

In [24]:
np.linspace(0,10,10)

array([ 0.        ,  1.11111111,  2.22222222,  3.33333333,  4.44444444,
        5.55555556,  6.66666667,  7.77777778,  8.88888889, 10.        ])

In [25]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [26]:
np.random.rand(10)

array([0.04359023, 0.83774839, 0.59614117, 0.93309679, 0.17710015,
       0.40122392, 0.76568056, 0.4313206 , 0.71655784, 0.51666874])

In [27]:
np.random.rand(5,5)

array([[0.56460509, 0.33469904, 0.80905157, 0.40032822, 0.81638489],
       [0.90475152, 0.89547515, 0.16361267, 0.52113467, 0.72466385],
       [0.3476067 , 0.21118755, 0.00403063, 0.21190937, 0.17957741],
       [0.55940507, 0.78392855, 0.05351288, 0.81505153, 0.20361916],
       [0.02610281, 0.56044918, 0.8429841 , 0.58345805, 0.95366017]])

In [28]:
np.random.randint(1,100,10)

array([22, 65, 68, 85, 99,  5, 74, 89, 64, 46])

In [29]:
arr = np.arange(50)

In [30]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49])

In [32]:
ar = np.random.rand(50)

In [33]:
ar

array([0.75117007, 0.66855704, 0.5206777 , 0.81949309, 0.31013598,
       0.43147329, 0.82013508, 0.15803537, 0.64258141, 0.82696902,
       0.98245064, 0.95016379, 0.77136293, 0.99877755, 0.43849311,
       0.10103537, 0.02552708, 0.24886568, 0.16642153, 0.72378251,
       0.18109735, 0.91650911, 0.51175713, 0.92928596, 0.6374352 ,
       0.79643395, 0.66900017, 0.38039373, 0.15290952, 0.77626238,
       0.63174077, 0.89492774, 0.02042993, 0.92260196, 0.25243525,
       0.91274659, 0.6378671 , 0.40109978, 0.25555776, 0.04355315,
       0.54199072, 0.72341097, 0.04101742, 0.6333777 , 0.11751471,
       0.95564929, 0.44630489, 0.11426238, 0.68802882, 0.67803587])

In [36]:
ranarr = np.random.randint(0,50,50)

In [37]:
ranarr

array([33, 16, 28, 30,  4, 15, 31,  3, 16, 45, 36, 34,  8, 15,  7, 42, 12,
       16, 42,  8, 11, 10, 44,  6,  7,  6, 34, 49,  7, 10, 15, 12,  6,  1,
       43, 44,  6, 39, 29, 16, 48, 23, 49, 40, 22,  9, 16, 41, 23, 28])

In [38]:
ranarr.reshape(5,10)

array([[33, 16, 28, 30,  4, 15, 31,  3, 16, 45],
       [36, 34,  8, 15,  7, 42, 12, 16, 42,  8],
       [11, 10, 44,  6,  7,  6, 34, 49,  7, 10],
       [15, 12,  6,  1, 43, 44,  6, 39, 29, 16],
       [48, 23, 49, 40, 22,  9, 16, 41, 23, 28]])

In [39]:
ranarr.max()

49

In [40]:
ranarr.min()

1

In [44]:
ranarr.argmin()

33

In [45]:
ranarr.shape()

TypeError: 'tuple' object is not callable

In [46]:
ranarr = ranarr.reshape(10,5)

In [47]:
ranarr

array([[33, 16, 28, 30,  4],
       [15, 31,  3, 16, 45],
       [36, 34,  8, 15,  7],
       [42, 12, 16, 42,  8],
       [11, 10, 44,  6,  7],
       [ 6, 34, 49,  7, 10],
       [15, 12,  6,  1, 43],
       [44,  6, 39, 29, 16],
       [48, 23, 49, 40, 22],
       [ 9, 16, 41, 23, 28]])

In [48]:
ranarr.argmax()

27

In [49]:
ranarr.argmin()

33

In [50]:
ranarr.shape

(10, 5)

In [51]:
ranarr.dtype

dtype('int32')

In [52]:
arr = np.arange(0,12)

In [53]:
arr[0:5]

array([0, 1, 2, 3, 4])

In [54]:
arr[5:]

array([ 5,  6,  7,  8,  9, 10, 11])

In [55]:
arr[:]

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [56]:
arr[0:5] = 5
print(arr)

[ 5  5  5  5  5  5  6  7  8  9 10 11]


In [57]:
arr = np.arange(50)

In [58]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49])

In [59]:
arr  - arr

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0])

In [60]:
arr + arr

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32,
       34, 36, 38, 40, 42, 44, 46, 48, 50, 52, 54, 56, 58, 60, 62, 64, 66,
       68, 70, 72, 74, 76, 78, 80, 82, 84, 86, 88, 90, 92, 94, 96, 98])

In [61]:
arr * arr

array([   0,    1,    4,    9,   16,   25,   36,   49,   64,   81,  100,
        121,  144,  169,  196,  225,  256,  289,  324,  361,  400,  441,
        484,  529,  576,  625,  676,  729,  784,  841,  900,  961, 1024,
       1089, 1156, 1225, 1296, 1369, 1444, 1521, 1600, 1681, 1764, 1849,
       1936, 2025, 2116, 2209, 2304, 2401])

In [62]:
np.sqrt(arr ** 2)

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.,
       13., 14., 15., 16., 17., 18., 19., 20., 21., 22., 23., 24., 25.,
       26., 27., 28., 29., 30., 31., 32., 33., 34., 35., 36., 37., 38.,
       39., 40., 41., 42., 43., 44., 45., 46., 47., 48., 49.])

In [63]:
np.exp(arr)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03, 2.20264658e+04, 5.98741417e+04,
       1.62754791e+05, 4.42413392e+05, 1.20260428e+06, 3.26901737e+06,
       8.88611052e+06, 2.41549528e+07, 6.56599691e+07, 1.78482301e+08,
       4.85165195e+08, 1.31881573e+09, 3.58491285e+09, 9.74480345e+09,
       2.64891221e+10, 7.20048993e+10, 1.95729609e+11, 5.32048241e+11,
       1.44625706e+12, 3.93133430e+12, 1.06864746e+13, 2.90488497e+13,
       7.89629602e+13, 2.14643580e+14, 5.83461743e+14, 1.58601345e+15,
       4.31123155e+15, 1.17191424e+16, 3.18559318e+16, 8.65934004e+16,
       2.35385267e+17, 6.39843494e+17, 1.73927494e+18, 4.72783947e+18,
       1.28516001e+19, 3.49342711e+19, 9.49611942e+19, 2.58131289e+20,
       7.01673591e+20, 1.90734657e+21])

In [64]:
np.sin(arr)

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ,
       -0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849,
       -0.54402111, -0.99999021, -0.53657292,  0.42016704,  0.99060736,
        0.65028784, -0.28790332, -0.96139749, -0.75098725,  0.14987721,
        0.91294525,  0.83665564, -0.00885131, -0.8462204 , -0.90557836,
       -0.13235175,  0.76255845,  0.95637593,  0.27090579, -0.66363388,
       -0.98803162, -0.40403765,  0.55142668,  0.99991186,  0.52908269,
       -0.42818267, -0.99177885, -0.64353813,  0.29636858,  0.96379539,
        0.74511316, -0.15862267, -0.91652155, -0.83177474,  0.01770193,
        0.85090352,  0.90178835,  0.12357312, -0.76825466, -0.95375265])

In [65]:
np.log(arr)

C:\Users\GodHand\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in log
  """Entry point for launching an IPython kernel.


array([      -inf, 0.        , 0.69314718, 1.09861229, 1.38629436,
       1.60943791, 1.79175947, 1.94591015, 2.07944154, 2.19722458,
       2.30258509, 2.39789527, 2.48490665, 2.56494936, 2.63905733,
       2.7080502 , 2.77258872, 2.83321334, 2.89037176, 2.94443898,
       2.99573227, 3.04452244, 3.09104245, 3.13549422, 3.17805383,
       3.21887582, 3.25809654, 3.29583687, 3.33220451, 3.36729583,
       3.40119738, 3.4339872 , 3.4657359 , 3.49650756, 3.52636052,
       3.55534806, 3.58351894, 3.61091791, 3.63758616, 3.66356165,
       3.68887945, 3.71357207, 3.73766962, 3.76120012, 3.78418963,
       3.80666249, 3.8286414 , 3.8501476 , 3.87120101, 3.8918203 ])

In [66]:
np.cos(arr)

array([ 1.        ,  0.54030231, -0.41614684, -0.9899925 , -0.65364362,
        0.28366219,  0.96017029,  0.75390225, -0.14550003, -0.91113026,
       -0.83907153,  0.0044257 ,  0.84385396,  0.90744678,  0.13673722,
       -0.75968791, -0.95765948, -0.27516334,  0.66031671,  0.98870462,
        0.40808206, -0.54772926, -0.99996083, -0.53283302,  0.42417901,
        0.99120281,  0.64691932, -0.29213881, -0.96260587, -0.74805753,
        0.15425145,  0.91474236,  0.83422336, -0.01327675, -0.84857027,
       -0.90369221, -0.12796369,  0.76541405,  0.95507364,  0.26664293,
       -0.66693806, -0.98733928, -0.39998531,  0.5551133 ,  0.99984331,
        0.52532199, -0.43217794, -0.99233547, -0.64014434,  0.30059254])

In [67]:
np.max(arr)

49

In [68]:
np.min(arr)

0

In [69]:
np.argmax(arr)

49

In [70]:
import numpy as np

In [71]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [72]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [73]:
arr = np.ones(10)
arr = arr * 5
print(arr)

[5. 5. 5. 5. 5. 5. 5. 5. 5. 5.]


In [74]:
np.arange(10,51)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49, 50])

In [75]:
np.linspace(1,50,2)

array([ 1., 50.])

In [76]:
np.arange(1,50,2)

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29, 31, 33,
       35, 37, 39, 41, 43, 45, 47, 49])

In [77]:
np.arange(0,50,2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32,
       34, 36, 38, 40, 42, 44, 46, 48])

In [78]:
np.arange((3,3))

TypeError: arange: scalar arguments expected instead of a tuple.

In [79]:
np.arange(3,3)

array([], dtype=int32)