In [1]:
import numpy as np

In [2]:
ls = [1,2,3,4]


In [3]:
ls

[1, 2, 3, 4]

In [5]:
type(ls)

list

In [4]:
np.array(ls)

array([1, 2, 3, 4])

In [6]:
n1 = np.array(ls)

In [7]:
n1

array([1, 2, 3, 4])

In [8]:
type(n1)

numpy.ndarray

In [10]:
n2 = np.array([[1,2,3,4],[5,6,7,8]])

In [11]:
np

<module 'numpy' from 'C:\\Users\\GodHand\\Anaconda3\\lib\\site-packages\\numpy\\__init__.py'>

In [12]:
n3 = np.zeros((1,3))


In [14]:
n3

array([[0., 0., 0.]])

In [15]:
n4 = np.zeros((10,10))


In [16]:
n4

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

# initailize numpy array with same number


In [17]:
n5 = np.full((2,2),10)

In [18]:
n5

array([[10, 10],
       [10, 10]])

# Initalize numpy array with in range


In [20]:
n6 = np.arange(50,101)

In [21]:
n6

array([ 50,  51,  52,  53,  54,  55,  56,  57,  58,  59,  60,  61,  62,
        63,  64,  65,  66,  67,  68,  69,  70,  71,  72,  73,  74,  75,
        76,  77,  78,  79,  80,  81,  82,  83,  84,  85,  86,  87,  88,
        89,  90,  91,  92,  93,  94,  95,  96,  97,  98,  99, 100])

In [22]:
n7 = np.arange(50,500,10)

In [23]:
n7

array([ 50,  60,  70,  80,  90, 100, 110, 120, 130, 140, 150, 160, 170,
       180, 190, 200, 210, 220, 230, 240, 250, 260, 270, 280, 290, 300,
       310, 320, 330, 340, 350, 360, 370, 380, 390, 400, 410, 420, 430,
       440, 450, 460, 470, 480, 490])

# Initialize numpy array with random numbers

In [24]:
n8 = np.random.randint(100,200,10)

In [25]:
n8

array([103, 169, 182, 117, 183, 159, 196, 173, 119, 145])

In [26]:
n8.shape

(10,)

In [27]:
n7.shape

(45,)

In [28]:
n9 = np.array([[1,2,3],[4,5,6]])

In [29]:
n9.shape

(2, 3)

In [30]:
n9.shape = (3,2)

In [31]:
n9

array([[1, 2],
       [3, 4],
       [5, 6]])

In [32]:
n1 = np.array([1,2,3])

In [33]:
n2 = np.array([4,5,6])

# Join arrays vertically

In [35]:
n3 = np.vstack((n1,n2))

# Join array horizontally

In [37]:
n3 =np.hstack((n1,n2))

# Join array column wise

In [38]:
n3 = np.column_stack((n1,n2))

# Intersection

In [39]:
n1 = np.array([10,20,30,40,50,60])

In [40]:
n2 = np.array([50,60,70,80,90])

In [41]:
np.intersect1d(n1,n2)

array([50, 60])

In [42]:
np.setdiff1d(n1,n2)

array([10, 20, 30, 40])

In [43]:
np.setdiff1d(n2,n1)

array([70, 80, 90])

In [47]:
n1 = np.array([10,20])

In [48]:
n2 = np.array([30,40])

In [49]:
np.sum([n1,n2])

100

In [50]:
np.sum([n1,n2] ,axis = 0)

array([40, 60])

In [51]:
np.sum([n1,n2] ,axis = 1)

array([30, 70])