In [1]:
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np

In [3]:
dataset = pd.read_csv('Social_Network_Ads.csv')

In [4]:
dataset

User ID  Gender   Age  EstimatedSalary  Purchased
0    15624510    Male  19.0          19000.0          0
1    15810944    Male  35.0          20000.0          0
2    15668575  Female  26.0          43000.0          0
3    15603246  Female  27.0          57000.0          0
4    15804002    Male  19.0          76000.0          0
..        ...     ...   ...              ...        ...
395  15691863  Female  46.0          41000.0          1
396  15706071    Male  51.0          23000.0          1
397  15654296  Female  50.0          20000.0          1
398  15755018    Male  36.0          33000.0          0
399  15594041  Female  49.0          36000.0          1

[400 rows x 5 columns]

In [5]:
dataset.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 400 entries, 0 to 399
Data columns (total 5 columns):
User ID            400 non-null int64
Gender             400 non-null object
Age                400 non-null float64
EstimatedSalary    400 non-null float64
Purchased          400 non-null int64
dtypes: float64(2), int64(2), object(1)
memory usage: 15.8+ KB


In [6]:
dataset.describe()

User ID         Age  EstimatedSalary   Purchased
count  4.000000e+02  400.000000       400.000000  400.000000
mean   1.569154e+07   37.655000     69742.500000    0.357500
std    7.165832e+04   10.482877     34096.960282    0.479864
min    1.556669e+07   18.000000     15000.000000    0.000000
25%    1.562676e+07   29.750000     43000.000000    0.000000
50%    1.569434e+07   37.000000     70000.000000    0.000000
75%    1.575036e+07   46.000000     88000.000000    1.000000
max    1.581524e+07   60.000000    150000.000000    1.000000

In [7]:
X = dataset.iloc[:,[2,3]].values
y = dataset.iloc[:,4].values
                 

In [8]:
X

array([[1.90e+01, 1.90e+04],
       [3.50e+01, 2.00e+04],
       [2.60e+01, 4.30e+04],
       [2.70e+01, 5.70e+04],
       [1.90e+01, 7.60e+04],
       [2.70e+01, 5.80e+04],
       [2.70e+01, 8.40e+04],
       [3.20e+01, 1.50e+05],
       [2.50e+01, 3.30e+04],
       [3.50e+01, 6.50e+04],
       [2.60e+01, 8.00e+04],
       [2.60e+01, 5.20e+04],
       [2.00e+01, 8.60e+04],
       [3.20e+01, 1.80e+04],
       [1.80e+01, 8.20e+04],
       [2.90e+01, 8.00e+04],
       [4.70e+01, 2.50e+04],
       [4.50e+01, 2.60e+04],
       [4.60e+01, 2.80e+04],
       [4.80e+01, 2.90e+04],
       [4.50e+01, 2.20e+04],
       [4.70e+01, 4.90e+04],
       [4.80e+01, 4.10e+04],
       [4.50e+01, 2.20e+04],
       [4.60e+01, 2.30e+04],
       [4.70e+01, 2.00e+04],
       [4.90e+01, 2.80e+04],
       [4.70e+01, 3.00e+04],
       [2.90e+01, 4.30e+04],
       [3.10e+01, 1.80e+04],
       [3.10e+01, 7.40e+04],
       [2.70e+01, 1.37e+05],
       [2.10e+01, 1.60e+04],
       [2.80e+01, 4.40e+04],
       [2.70e+

In [9]:
y

array([0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1,
       0, 1, 1, 1, 0, 0, 1, 1, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 0, 1, 1, 0,
       1, 1, 0, 1, 0, 1, 0, 1, 0, 0, 1, 1, 0, 1, 0, 0, 1, 1, 0, 1, 1, 0,
       1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 0, 1,
       0, 1, 0, 1, 1, 1, 1, 0, 0, 0, 1, 1, 0, 1, 1,

In [10]:
from sklearn.model_selection import train_test_split

In [11]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.25, random_state=42)

In [12]:
X_train

array([[5.70e+01, 1.22e+05],
       [3.90e+01, 7.10e+04],
       [4.70e+01, 2.50e+04],
       [2.40e+01, 1.90e+04],
       [3.60e+01, 5.00e+04],
       [3.20e+01, 1.50e+05],
       [4.80e+01, 2.90e+04],
       [3.00e+01, 1.07e+05],
       [6.00e+01, 3.40e+04],
       [3.80e+01, 6.10e+04],
       [3.30e+01, 3.10e+04],
       [3.90e+01, 7.10e+04],
       [5.50e+01, 3.90e+04],
       [4.90e+01, 3.90e+04],
       [4.30e+01, 1.12e+05],
       [2.70e+01, 2.00e+04],
       [2.60e+01, 1.70e+04],
       [3.70e+01, 9.30e+04],
       [4.20e+01, 5.40e+04],
       [3.50e+01, 6.10e+04],
       [2.90e+01, 7.50e+04],
       [3.80e+01, 8.00e+04],
       [4.50e+01, 2.60e+04],
       [5.40e+01, 1.08e+05],
       [4.60e+01, 2.30e+04],
       [2.30e+01, 2.80e+04],
       [3.70e+01, 7.50e+04],
       [4.20e+01, 6.50e+04],
       [3.50e+01, 7.10e+04],
       [5.10e+01, 1.46e+05],
       [3.90e+01, 9.60e+04],
       [2.40e+01, 8.90e+04],
       [5.80e+01, 9.50e+04],
       [2.50e+01, 2.20e+04],
       [4.10e+

In [13]:
X_test

array([[4.60e+01, 2.20e+04],
       [5.90e+01, 8.80e+04],
       [2.80e+01, 4.40e+04],
       [4.80e+01, 9.60e+04],
       [2.90e+01, 2.80e+04],
       [3.00e+01, 6.20e+04],
       [4.70e+01, 1.07e+05],
       [2.90e+01, 8.30e+04],
       [4.00e+01, 7.50e+04],
       [4.20e+01, 6.50e+04],
       [3.50e+01, 6.50e+04],
       [5.30e+01, 3.40e+04],
       [2.30e+01, 4.80e+04],
       [2.00e+01, 2.30e+04],
       [3.00e+01, 8.70e+04],
       [3.50e+01, 1.08e+05],
       [5.20e+01, 3.80e+04],
       [4.60e+01, 7.40e+04],
       [3.90e+01, 4.20e+04],
       [5.60e+01, 6.00e+04],
       [2.20e+01, 2.70e+04],
       [2.90e+01, 8.00e+04],
       [4.70e+01, 2.30e+04],
       [5.90e+01, 7.60e+04],
       [1.90e+01, 1.90e+04],
       [5.10e+01, 2.30e+04],
       [4.20e+01, 8.00e+04],
       [3.70e+01, 5.30e+04],
       [5.50e+01, 1.25e+05],
       [1.90e+01, 2.10e+04],
       [4.60e+01, 4.10e+04],
       [1.90e+01, 7.00e+04],
       [3.60e+01, 1.44e+05],
       [2.80e+01, 7.90e+04],
       [4.00e+

In [16]:
from sklearn.preprocessing import StandardScaler

In [18]:
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [19]:
X_train

array([[ 1.8925893 ,  1.52189404],
       [ 0.1250379 ,  0.03213212],
       [ 0.9106163 , -1.31157471],
       [-1.34792161, -1.48684082],
       [-0.169554  , -0.58129926],
       [-0.56234321,  2.33980255],
       [ 1.0088136 , -1.19473064],
       [-0.75873781,  1.08372877],
       [ 2.1871812 , -1.04867555],
       [ 0.0268406 , -0.25997806],
       [-0.46414591, -1.1363086 ],
       [ 0.1250379 ,  0.03213212],
       [ 1.6961947 , -0.90262046],
       [ 1.1070109 , -0.90262046],
       [ 0.5178271 ,  1.22978386],
       [-1.05332971, -1.4576298 ],
       [-1.15152701, -1.54526286],
       [-0.0713567 ,  0.67477452],
       [ 0.4196298 , -0.46445519],
       [-0.2677513 , -0.25997806],
       [-0.85693511,  0.14897619],
       [ 0.0268406 ,  0.29503128],
       [ 0.7142217 , -1.28236369],
       [ 1.5979974 ,  1.11293979],
       [ 0.812419  , -1.36999675],
       [-1.44611891, -1.22394166],
       [-0.0713567 ,  0.14897619],
       [ 0.4196298 , -0.14313399],
       [-0.2677513 ,